/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "gpio_driver.h"

int main(void)
{
	// test GPIO
    gpio::init_gpio(GPIOB, 11, MODE_OUTPUT_10MHZ, CNF_OUTPUT_PUSH_PULL);
    gpio::SetHIGH(GPIOB, 11);

    // to-do : gpio config structure
	for(;;);
}
